name: share_specified_app
description: A Flutter plugin for sharing file to specified app. Only support Android.
version: 0.0.1
repository: https://github.com/linyi102/share_specified_app

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.linyi.share_specified_app
        pluginClass: ShareSpecifiedAppPlugin
